version: "3.9"

services:
  mysql:
    image: mysql:latest
    platform: linux/arm64
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ../.env.dev
