POST http://127.0.0.1:5000/schedule/ HTTP/1.1
Content-Type: application/json

{
    "uid" : "test",
    "startingDate" : "2020-10-01",
    "endingDate" : "2020-10-01",
    "startingTime" : "10:00",
    "endingTime" : "12:00",
    "item": "testitem",
    "spendingAmount" : 10000,
    "incomeAmount" : 5000
}

###
GET http://127.0.0.1:5000/schedule/test/2020/10 HTTP/1.1

###
GET http://127.0.0.1:5000/schedule/test/2020/10/01 HTTP/1.1

###
POST http://127.0.0.1:5000/payment/ HTTP/1.1
Content-Type: application/json

{
    "uid" : "test",
    "spendingAmount" : 10000,
    "date" : "2020-10"
}
###
GET http://127.0.0.1:5000/payment/test/2020/10 HTTP/1.1

###
POST http://127.0.0.1:5000/payment/ HTTP/1.1
Content-Type: application/json

{
    "uid" : "test",
    "spendingAmount" : 20000,
    "date" : "2020-10"
}