POST http://127.0.0.1:5000/schedule/ HTTP/1.1
Content-Type: application/json

{
    "uid": "nanana",
    "startingDateTime": "2023-01-11T00:00",
    "endingDateTime": "2023-01-11T12:00",
    "item": "アルバイト",
    "spendingAmount": 10000,
    "incomeAmount": 100
}

###
GET http://127.0.0.1:5000/schedule/nanana/2023/1 HTTP/1.1

###
GET http://127.0.0.1:5000/schedule/nanana/2023/1/11 HTTP/1.1

###
DELETE  http://127.0.0.1:5000/schedule/1 HTTP/1.1

###
PUT http://127.0.0.1:5000/schedule/ HTTP/1.1
Content-Type: application/json

# {
#     "id": 1,
#     "uid": "nanana",
#     "startingDateTime": "2023-01-11T00:00",
#     "endingDateTime": "2023-01-11T12:00",
#     "item": "カラオケ",
#     "spendingAmount": 1500,
#     "incomeAmount": 0
# }
{
    "id": 1,
    "item": "カラオケ",
    "spendingAmount": 1500,
    "incomeAmount": 0
}

###
POST http://127.0.0.1:5000/payment/ HTTP/1.1
Content-Type: application/json

{
    "uid" : "nanana",
    "spendingAmount" : 100001,
    "date" : "2023-01"
}

###
# GET http://127.0.0.1:5000/payment/nanana/2023/01 HTTP/1.1

